<?php

namespace ContainerDWlVN6E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KPLc8w3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KPLc8w3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KPLc8w3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\FindController::changeVilles' => ['privates', '.service_locator.vqbRAJs', 'get_ServiceLocator_VqbRAJsService', true],
            'App\\Controller\\FindController::corporations' => ['privates', '.service_locator.xfDPf.V', 'get_ServiceLocator_XfDPf_VService', true],
            'App\\Controller\\FindController::rechercheCorporations' => ['privates', '.service_locator.xfDPf.V', 'get_ServiceLocator_XfDPf_VService', true],
            'App\\Controller\\FindController::villes' => ['privates', '.service_locator.vqbRAJs', 'get_ServiceLocator_VqbRAJsService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\SecurityController::subscribe' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\SecurityController::subscribeValidation' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\FindController:changeVilles' => ['privates', '.service_locator.vqbRAJs', 'get_ServiceLocator_VqbRAJsService', true],
            'App\\Controller\\FindController:corporations' => ['privates', '.service_locator.xfDPf.V', 'get_ServiceLocator_XfDPf_VService', true],
            'App\\Controller\\FindController:rechercheCorporations' => ['privates', '.service_locator.xfDPf.V', 'get_ServiceLocator_XfDPf_VService', true],
            'App\\Controller\\FindController:villes' => ['privates', '.service_locator.vqbRAJs', 'get_ServiceLocator_VqbRAJsService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\SecurityController:subscribe' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\SecurityController:subscribeValidation' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\FindController::changeVilles' => '?',
            'App\\Controller\\FindController::corporations' => '?',
            'App\\Controller\\FindController::rechercheCorporations' => '?',
            'App\\Controller\\FindController::villes' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::subscribe' => '?',
            'App\\Controller\\SecurityController::subscribeValidation' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\FindController:changeVilles' => '?',
            'App\\Controller\\FindController:corporations' => '?',
            'App\\Controller\\FindController:rechercheCorporations' => '?',
            'App\\Controller\\FindController:villes' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:subscribe' => '?',
            'App\\Controller\\SecurityController:subscribeValidation' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
