<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBiIK5Wi\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBiIK5Wi/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerBiIK5Wi.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerBiIK5Wi\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerBiIK5Wi\App_KernelProdContainer([
    'container.build_hash' => 'BiIK5Wi',
    'container.build_id' => 'f2c4d451',
    'container.build_time' => 1688068204,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBiIK5Wi');
