<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTnGhCsh\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTnGhCsh/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerTnGhCsh.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerTnGhCsh\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerTnGhCsh\App_KernelProdContainer([
    'container.build_hash' => 'TnGhCsh',
    'container.build_id' => 'a2180429',
    'container.build_time' => 1688122384,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTnGhCsh');
