<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'ville' => [['country'], ['_controller' => 'App\\Controller\\FindController::villes'], [], [['text', '/Villes'], ['variable', '/', '[^/]++', 'country', true], ['text', '/app/Localisation']], [], [], []],
    'change_ville' => [['country'], ['_controller' => 'App\\Controller\\FindController::changeVilles'], [], [['text', '/Villes/change'], ['variable', '/', '[^/]++', 'country', true], ['text', '/app/Localisation']], [], [], []],
    'corporations' => [['country', 'ville'], ['_controller' => 'App\\Controller\\FindController::corporations'], [], [['text', '/Corporations'], ['variable', '/', '[^/]++', 'ville', true], ['variable', '/', '[^/]++', 'country', true], ['text', '/app/Localisation']], [], [], []],
    'change_corporations' => [['country', 'ville'], ['_controller' => 'App\\Controller\\FindController::rechercheCorporations'], [], [['text', '/Corporations/change'], ['variable', '/', '[^/]++', 'ville', true], ['variable', '/', '[^/]++', 'country', true], ['text', '/app/Localisation']], [], [], []],
    'corporation' => [['country', 'ville', 'corpo'], ['_controller' => 'App\\Controller\\FindController::corporation'], [], [['variable', '/', '[^/]++', 'corpo', true], ['variable', '/', '[^/]++', 'ville', true], ['variable', '/', '[^/]++', 'country', true], ['text', '/app/Localisation']], [], [], []],
    'corporation_html' => [[], ['_controller' => 'App\\Controller\\FindController::corporationHtml'], [], [['text', '/Localisation/corporation']], [], [], []],
    'connexions' => [[], ['_controller' => 'App\\Controller\\HomeController::connexions'], [], [['text', '/app/connexions']], [], [], []],
    'calendar' => [[], ['_controller' => 'App\\Controller\\HomeController::calendar'], [], [['text', '/app/calendar']], [], [], []],
    'accueil' => [[], ['_controller' => 'App\\Controller\\HomeController::accueil'], [], [['text', '/app/accueil']], [], [], []],
    'revisions' => [[], ['_controller' => 'App\\Controller\\HomeController::revisions'], [], [['text', '/app/revisions']], [], [], []],
    'profile' => [[], ['_controller' => 'App\\Controller\\ProfileController::profile'], [], [['text', '/app/profile']], [], [], []],
    'modification_informations' => [[], ['_controller' => 'App\\Controller\\ProfileController::modificationInformations'], [], [['text', '/app/modification/informations']], [], [], []],
    'modification_informations_patch' => [[], ['_controller' => 'App\\Controller\\ProfileController::patchModificationInformations'], [], [['text', '/app/modification/informations/patch']], [], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/app/login']], [], [], []],
    'subscribe' => [[], ['_controller' => 'App\\Controller\\SecurityController::subscribe'], [], [['text', '/app/subscribe']], [], [], []],
    'subscribe_validation' => [[], ['_controller' => 'App\\Controller\\SecurityController::subscribeValidation'], [], [['text', '/app/subscribe/validation']], [], [], []],
    'logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/app/logout']], [], [], []],
    'auth_ajax_subscribe' => [[], ['_controller' => 'App\\Controller\\SecurityController::ajaxSubscribe'], [], [['text', '/app/auth/subscribe']], [], [], []],
    'forgot_password' => [[], ['_controller' => 'App\\Controller\\SecurityController::forgotPassword'], [], [['text', '/app/forgot/password']], [], [], []],
    'send_reset_request_password' => [[], ['_controller' => 'App\\Controller\\SecurityController::sendRequestResetPassword'], [], [['text', '/app/forgot/password/request']], [], [], []],
];
