<?php

namespace ContainerKZxUxMx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRevisionsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\RevisionsController' shared autowired service.
     *
     * @return \App\Controller\RevisionsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/RevisionsController.php';

        $container->services['App\\Controller\\RevisionsController'] = $instance = new \App\Controller\RevisionsController(($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()), ($container->privates['App\\Service\\FindApiService'] ?? $container->load('getFindApiServiceService')), ($container->privates['App\\Service\\FindAuthService'] ?? $container->load('getFindAuthServiceService')));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\RevisionsController', $container));

        return $instance;
    }
}
