<?php

namespace ContainerWzrWBRr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_El0U_9OService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.el0U.9O' shared service.
     *
     * @return \App\Repository\DecorumRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\FindController::corporation()": the $decorumRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\DecorumRepository".');
    }
}
