<?php

namespace ContainerWzrWBRr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_3TUkKfXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.3TUkKfX' shared service.
     *
     * @return \App\Repository\ParticularitesRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\FindController::corporation()": the $particularitesRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\ParticularitesRepository".');
    }
}
