<?php

<<<<<<<< HEAD:var/cache/prod/Container7NVebJA/get_Console_Command_AssetsInstall_LazyService.php
namespace Container7NVebJA;
========
namespace ContainerW9yxFhx;
>>>>>>>> 3af3e57b67cf80732ba95f3617618de2e0d66dc1:var/cache/prod/ContainerW9yxFhx/get_Console_Command_AssetsInstall_LazyService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Console_Command_AssetsInstall_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.console.command.assets_install.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.console.command.assets_install.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('assets:install', [], 'Install bundle\'s web assets under a public directory', false, function () use ($container): \Symfony\Bundle\FrameworkBundle\Command\AssetsInstallCommand {
            return ($container->privates['console.command.assets_install'] ?? $container->load('getConsole_Command_AssetsInstallService'));
        });
    }
}
