<?php

<<<<<<<< HEAD:var/cache/prod/Container7NVebJA/getConsole_Command_ContainerDebugService.php
namespace Container7NVebJA;
========
namespace ContainerW9yxFhx;
>>>>>>>> 3af3e57b67cf80732ba95f3617618de2e0d66dc1:var/cache/prod/ContainerW9yxFhx/getConsole_Command_ContainerDebugService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_Command_ContainerDebugService extends App_KernelProdContainer
{
    /*
     * Gets the private 'console.command.container_debug' shared service.
     *
     * @return \Symfony\Bundle\FrameworkBundle\Command\ContainerDebugCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['console.command.container_debug'] = $instance = new \Symfony\Bundle\FrameworkBundle\Command\ContainerDebugCommand();

        $instance->setName('debug:container');
        $instance->setDescription('Display current services for an application');

        return $instance;
    }
}
