<?php

<<<<<<<< HEAD:var/cache/prod/Container7NVebJA/getForm_TypeGuesser_DoctrineService.php
namespace Container7NVebJA;
========
namespace ContainerW9yxFhx;
>>>>>>>> 3af3e57b67cf80732ba95f3617618de2e0d66dc1:var/cache/prod/ContainerW9yxFhx/getForm_TypeGuesser_DoctrineService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_TypeGuesser_DoctrineService extends App_KernelProdContainer
{
    /*
     * Gets the private 'form.type_guesser.doctrine' shared service.
     *
     * @return \Symfony\Bridge\Doctrine\Form\DoctrineOrmTypeGuesser
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['form.type_guesser.doctrine'] = new \Symfony\Bridge\Doctrine\Form\DoctrineOrmTypeGuesser(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
