<?php

<<<<<<<< HEAD:var/cache/prod/Container7NVebJA/getSecurity_AuthenticationUtilsService.php
namespace Container7NVebJA;
========
namespace ContainerW9yxFhx;
>>>>>>>> 3af3e57b67cf80732ba95f3617618de2e0d66dc1:var/cache/prod/ContainerW9yxFhx/getSecurity_AuthenticationUtilsService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_AuthenticationUtilsService extends App_KernelProdContainer
{
    /*
     * Gets the private 'security.authentication_utils' shared service.
     *
     * @return \Symfony\Component\Security\Http\Authentication\AuthenticationUtils
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['security.authentication_utils'] = new \Symfony\Component\Security\Http\Authentication\AuthenticationUtils(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
