<?php

namespace ContainerW9yxFhx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Authenticator_Guard_Main_0Service extends App_KernelProdContainer
{
    /*
     * Gets the private 'security.authenticator.guard.main.0' shared service.
     *
     * @return \Symfony\Component\Security\Guard\Authenticator\GuardBridgeAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['App\\Security\\UserProvider'] ?? $container->load('getUserProviderService'));

        return $container->privates['security.authenticator.guard.main.0'] = new \Symfony\Component\Security\Guard\Authenticator\GuardBridgeAuthenticator(new \App\Security\TokenAuthenticator(($container->services['router'] ?? $container->getRouterService()), ($container->services['.container.private.security.csrf.token_manager'] ?? $container->load('get_Container_Private_Security_Csrf_TokenManagerService')), ($container->privates['App\\Service\\FindAuthService'] ?? $container->load('getFindAuthServiceService')), ($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()), $a), $a);
    }
}
