<?php

namespace ContainerQAj9Nya;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_V_P2IT7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.v.P2IT7' shared service.
     *
     * @return \App\Entity\Corporations
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\FindController::corporation()": the $corporation argument is type-hinted with the non-existent class or interface: "App\\Entity\\Corporations".');
    }
}
