<?php

namespace ContainerVM3ffLs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFindAuthServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\FindAuthService' shared autowired service.
     *
     * @return \App\Service\FindAuthService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/FindService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/FindAuthService.php';

        return $container->privates['App\\Service\\FindAuthService'] = new \App\Service\FindAuthService(($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()), $container->getEnv('resolve:FIND_AUTH_URL'));
    }
}
