<?php

namespace ContainerSSiMSLh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_JQi6e0WService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.jQi6e0W' shared service.
     *
     * @return \App\Repository\PinsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\FindController::corporation()": the $pinsRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\PinsRepository".');
    }
}
