<?php

namespace ContainerTnGhCsh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCorporationsRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\CorporationsRepository' shared autowired service.
     *
     * @return \App\Repository\CorporationsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\CorporationsRepository'] = new \App\Repository\CorporationsRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
