<?php

namespace ContainerTnGhCsh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFindApiServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\FindApiService' shared autowired service.
     *
     * @return \App\Service\FindApiService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\FindApiService'] = new \App\Service\FindApiService(($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()), $container->getEnv('resolve:FIND_API_URL'));
    }
}
