<?php

namespace Container0KMYnGv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_IQi28HdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.IQi28Hd' shared service.
     *
     * @return \App\Repository\CorporationsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\FindController::corporations()": the $corporationsRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\CorporationsRepository".');
    }
}
