<?php

namespace Container0KMYnGv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_WATacW7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.wATacW7' shared service.
     *
     * @return \App\Repository\VilleRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\FindController::rechercheCorporations()": the $villeRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\VilleRepository".');
    }
}
