<?php

namespace Container0KMYnGv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FcXBAcDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FcXBAcD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FcXBAcD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'villeRepository' => ['privates', '.errored.2C2Q2WE', NULL, 'Cannot determine controller argument for "App\\Controller\\FindController::changeVilles()": the $villeRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\VilleRepository".'],
        ], [
            'villeRepository' => '?',
        ]);
    }
}
