<?php

namespace Container0KMYnGv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ukm4lLdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ukm4lLd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ukm4lLd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'corporationsRepository' => ['privates', '.errored.IQi28Hd', NULL, 'Cannot determine controller argument for "App\\Controller\\FindController::corporations()": the $corporationsRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\CorporationsRepository".'],
            'villeRepository' => ['privates', '.errored.ZN4uaMK', NULL, 'Cannot determine controller argument for "App\\Controller\\FindController::corporations()": the $villeRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\VilleRepository".'],
        ], [
            'corporationsRepository' => '?',
            'villeRepository' => '?',
        ]);
    }
}
