<?php

namespace Container0KMYnGv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LlkM_1_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.llkM.1.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.llkM.1.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'corporationsRepository' => ['privates', '.errored.eY3bdVD', NULL, 'Cannot determine controller argument for "App\\Controller\\FindController::rechercheCorporations()": the $corporationsRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\CorporationsRepository".'],
            'villeRepository' => ['privates', '.errored.wATacW7', NULL, 'Cannot determine controller argument for "App\\Controller\\FindController::rechercheCorporations()": the $villeRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\VilleRepository".'],
        ], [
            'corporationsRepository' => '?',
            'villeRepository' => '?',
        ]);
    }
}
