<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX7RB6Tp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX7RB6Tp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX7RB6Tp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX7RB6Tp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX7RB6Tp\App_KernelDevDebugContainer([
    'container.build_hash' => 'X7RB6Tp',
    'container.build_id' => '40bc1d20',
    'container.build_time' => 1688068253,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX7RB6Tp');
