<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJrHxN5s\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJrHxN5s/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJrHxN5s.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJrHxN5s\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJrHxN5s\App_KernelDevDebugContainer([
    'container.build_hash' => 'JrHxN5s',
    'container.build_id' => '3a1c2098',
    'container.build_time' => 1686680447,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJrHxN5s');
